/*==============================================================*/
/* Usuario                                                     */
/*==============================================================*/

INSERT INTO Usuario VALUES (S_USUARIO.NEXTVAL, 'gustavo','$2a$10$AEMBf.4hcftpIAKcUuWpbeYRI5HYNZZlP7cDSTetbRyCSEyq0d1Nq','gustavopineda400@gmail.com',0,0,1);

/*==============================================================*/
/* Rol                                                        */
/*==============================================================*/

INSERT INTO Rol VALUES (S_ROL.NEXTVAL, 'ADMINISTRADOR');

/*==============================================================*/
/* usuario_roles                                                */
/*==============================================================*/

INSERT INTO usuario_rol VALUES (1,1);

/*==============================================================*/
/* Permiso                                                      */
/*==============================================================*/

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_USUARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_USUARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_USUARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_USUARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_USUARIO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_ROL_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_ROL_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_ROL_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_ROL_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_ROL_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_BITACORA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_BITACORA_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_TERRENO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_TERRENO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_TERRENO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_TERRENO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_TERRENO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_TERRENO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_PROYECTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_PROYECTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_PROYECTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_PROYECTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_PROYECTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_PROYECTO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_EMPRESA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_EMPRESA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_EMPRESA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_EMPRESA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_EMPRESA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_EMPRESA_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'SELECCIONAR_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_PROPIETARIO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_CORREO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_CORREO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_TELEFONO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_TELEFONO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_REFERENCIA_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_REFERENCIA_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_DOCUMENTO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_DOCUMENTO_PROPIETARIO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_DOCUMENTO_PROPIETARIO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'SELECCIONAR_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_TRABAJADOR_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_DOCUMENTO_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_DOCUMENTO_TRABAJADOR_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_DOCUMENTO_TRABAJADOR_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_VENTA_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_INFORMACION_FINANCIAMIENTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_INFORMACION_MANTENIMIENTO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_DOCUMENTO_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_DOCUMENTO_VENTA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_DOCUMENTO_VENTA_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ENVIO_CORREO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_FACTURACION_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_DATOS_PROYECTO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_PAGO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_PAGO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'VER_PAGO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_PAGO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_PAGO_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_PAGO_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_CUENTA_BANCARIA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EXPORTAR_CUENTA_BANCARIA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'AGREGAR_CUENTA_BANCARIA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'EDITAR_CUENTA_BANCARIA_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'ELIMINAR_CUENTA_BANCARIA_PRIVILAGE');

INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_MONITOREO_PAGOS_PRIVILAGE');
INSERT INTO Permiso VALUES (S_PERMISO.NEXTVAL, 'GESTIONAR_VISITAS_PROYECTO_PRIVILAGE');



/*==============================================================*/
/* roles_permisos                                               */
/*==============================================================*/

INSERT INTO rol_permiso VALUES (1,1);
INSERT INTO rol_permiso VALUES (1,2);
INSERT INTO rol_permiso VALUES (1,3);
INSERT INTO rol_permiso VALUES (1,4);
INSERT INTO rol_permiso VALUES (1,5);
INSERT INTO rol_permiso VALUES (1,6);
INSERT INTO rol_permiso VALUES (1,7);
INSERT INTO rol_permiso VALUES (1,8);
INSERT INTO rol_permiso VALUES (1,9);
INSERT INTO rol_permiso VALUES (1,10);
INSERT INTO rol_permiso VALUES (1,11);

INSERT INTO CONFIGURACION_CORREO (ID_CONFIGURACION, NAME, HOST, PORT, PROTOCOL, USERNAME, PASSWORD, SMTP_AUTH, START_TLS)
VALUES (S_CONFIGURACION_CORREO.NEXTVAL, 'Sistema Decatur', 'smtp.gmail.com', '587', 'smtp', 'mail.projects.notification@gmail.com', 'imiowrxsfxzmaopa', 1, 1);


